POST http://localhost:4004/rest/clientService/Cliente
Content-Type: application/json

{
  "Nombre": "Motorambar",
  "Division": "X05",
  "Gestor": "Marilyn",
  "Prioridad": "3",
  "Frecuencia": "Baja",
  "Integracion": "CPI",
  "BTP": "NEO",
  "to_ClienteLider": [
    {
      "to_Lider_ID": "67697718-697c-4cdf-901d-329a782ce02c"
    }
  ]
}
